services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_django_tailwind_starter
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: